services:
  caddy-proxy:
    container_name: caddy-proxy
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CF_API_TOKEN: "${CF_API_TOKEN}"
      CADDY_DOCKER_CADDYFILE_PATH: "/etc/caddy/Caddyfile"
      CADDY_INGRESS_NETWORKS: "proxy"
      DOCKER_API_VERSION: "1.44"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    external: true
