defmodule Slackex.Chat.Members do
  @moduledoc """
  Member management operations for channels.
  """

  import Ecto.Query

  alias Slackex.Accounts
  alias Slackex.Accounts.User
  alias Slackex.Chat.Channel
  alias Slackex.Chat.Permissions
  alias Slackex.Chat.Subscription
  alias Slackex.Repo

  @doc """
  Lists members of a channel with their user data and roles.
  Returns a list of maps with :user and :role keys.
  """
  def list_members(channel_id) do
    from(s in Subscription,
      where: s.channel_id == ^channel_id,
      join: u in assoc(s, :user),
      select: %{
        user: u,
        role: s.role,
        joined_at: s.inserted_at
      },
      order_by: [asc: s.inserted_at]
    )
    |> Repo.all()
  end

  @doc """
  Updates a member's role in a channel.
  Requires the actor to have manage_members permission.
  Cannot modify the channel owner.
  """
  def update_member_role(channel_id, actor_id, target_user_id, new_role) do
    with :ok <- authorize(actor_id, channel_id, :manage_members) do
      target_role = get_role(target_user_id, channel_id)

      cond do
        target_role == nil -> {:error, :not_a_member}
        target_role == "owner" -> {:error, :cannot_modify_owner}
        true -> do_update_role(channel_id, target_user_id, new_role)
      end
    end
  end

  @doc """
  Kicks a member from a channel.
  Requires the actor to have manage_members permission.
  Cannot kick the channel owner.
  """
  def kick_member(channel_id, actor_id, target_user_id) do
    with :ok <- authorize(actor_id, channel_id, :manage_members) do
      target_role = get_role(target_user_id, channel_id)

      cond do
        target_role == nil -> {:error, :not_a_member}
        target_role == "owner" -> {:error, :cannot_kick_owner}
        true -> do_kick(channel_id, target_user_id)
      end
    end
  end

  @doc """
  Subscribes a bot user to a public channel.

  Requires the actor to have `manage_members` permission (admin+). The target
  must be a bot (`is_bot: true`) and the channel public — mirroring the
  webhook-bot subscription constraints. Idempotent: subscribing an already
  subscribed bot returns `{:ok, :already_subscribed}`.

  Role is always `"member"`: a `viewer` bot would pass the MCP membership
  check yet fail `can?(:send_message)` — a silent write failure.
  """
  def add_bot_member(channel_id, actor_id, bot_user_id) do
    with :ok <- authorize(actor_id, channel_id, :manage_members),
         {:ok, channel} <- public_channel(channel_id),
         :ok <- ensure_bot(bot_user_id) do
      if get_role(bot_user_id, channel.id) do
        {:ok, :already_subscribed}
      else
        # Subscription has NO autogenerated id (@primary_key false, composite
        # user_id+channel_id), so the usual nil-id ghost-struct check cannot
        # detect a conflict — the ghost carries the changeset's own values.
        # The existence check above reports :already_subscribed; on_conflict
        # only guards the residual race window.
        %Subscription{}
        |> Subscription.changeset(%{user_id: bot_user_id, channel_id: channel.id, role: "member"})
        |> Repo.insert(on_conflict: :nothing, conflict_target: [:user_id, :channel_id])
      end
    end
  end

  @doc """
  Removes a bot user's subscription from a channel.

  Same `manage_members` gate as `kick_member/3` (to which it delegates), plus
  an `is_bot` assertion so this path cannot be used to kick human members.
  """
  def remove_bot_member(channel_id, actor_id, bot_user_id) do
    with :ok <- authorize(actor_id, channel_id, :manage_members),
         :ok <- ensure_bot(bot_user_id) do
      kick_member(channel_id, actor_id, bot_user_id)
    end
  end

  defp public_channel(channel_id) do
    case Repo.get(Channel, channel_id) do
      nil -> {:error, :channel_not_found}
      %Channel{is_private: true} -> {:error, :private_channel_not_supported}
      channel -> {:ok, channel}
    end
  end

  defp ensure_bot(user_id) do
    case Accounts.get_user(user_id) do
      %User{is_bot: true} -> :ok
      %User{} -> {:error, :not_a_bot}
      nil -> {:error, :bot_not_found}
    end
  end

  defp authorize(user_id, channel_id, action) do
    role = get_role(user_id, channel_id)

    if Permissions.can?(role, action), do: :ok, else: {:error, :unauthorized}
  end

  defp do_update_role(channel_id, user_id, new_role) do
    from(s in Subscription,
      where: s.user_id == ^user_id and s.channel_id == ^channel_id
    )
    |> Repo.update_all(set: [role: new_role])

    {:ok, new_role}
  end

  defp do_kick(channel_id, user_id) do
    from(s in Subscription,
      where: s.user_id == ^user_id and s.channel_id == ^channel_id
    )
    |> Repo.delete_all()

    :ok
  end

  defp get_role(user_id, channel_id) do
    Repo.one(
      from(s in Subscription,
        where: s.user_id == ^user_id and s.channel_id == ^channel_id,
        select: s.role
      )
    )
  end
end
