import Config

config :slackex, env: :dev

# Configure your database
config :slackex, Slackex.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "slackex_dev",
  port: 5434,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :slackex, Slackex.ReadRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "slackex_dev",
  port: 5434,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :slackex, SlackexWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jqBfhihnpPTnsta1cyRslGiihqECy2AZO1Ywdb8P9EdBo0AwB66GQQJs8KjliCW6",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:slackex, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:slackex, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :slackex, SlackexWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/slackex_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :slackex, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :libcluster,
  topologies: [
    gossip: [
      strategy: Cluster.Strategy.Gossip,
      config: [port: 45892]
    ]
  ]

config :slackex, :flags_admin_auth,
  username: "admin",
  password: "devpassword"

# OpenTelemetry — log traces to console in dev
config :opentelemetry,
  traces_exporter: {:otel_exporter_stdout, []}

# Use Bumblebee for real ML embeddings in development (all-MiniLM-L6-v2, 384-dim)
config :slackex, :embedding_client, Slackex.Embeddings.BumblebeeClient

# Use real LLM API in development (same as prod)
config :slackex, :llm_client, Slackex.AI.OpenAICompatibleClient
