import Config

config :slackex, env: :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :slackex, SlackexWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [hsts: true, rewrite_on: [:x_forwarded_proto]]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# StubClient — BumblebeeClient disabled until memory usage is resolved.
# CPU-only EXLA (EXLA_TARGET=host) works but model loading OOMs the 20GB Docker VM
# when both containers load simultaneously. See docs/rca/2026-03-05-*.md
config :slackex, :embedding_client, Slackex.Embeddings.StubClient

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
