defmodule SlackexWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :slackex

  @session_options [
    store: :cookie,
    key: "_slackex_key",
    signing_salt: "Vx7ryvLt",
    encryption_salt: "k8mR3qLw",
    same_site: "Lax",
    secure: Application.compile_env(:slackex, :env) == :prod,
    http_only: true
  ]

  socket "/socket", SlackexWeb.UserSocket,
    websocket: true,
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :slackex,
    gzip: not code_reloading?,
    only: SlackexWeb.static_paths()

  # Tidewave MCP server for AI-assisted development (dev only)
  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :slackex
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 1_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SlackexWeb.Router
end
